In [101]:
import numpy as np
from scipy.integrate import odeint
from scipy.optimize import curve_fit
from scipy.optimize import differential_evolution
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from scipy.interpolate import interp1d

In [102]:
xdata = [10,14,18,22,26,30,34,38,42,46,50,54,58,62,66]
tdata = [66.04,60.04,54.81,50.42,46.74,43.66,40.76,38.49,36.42,34.77,33.18,32.36,31.56,30.91,30.56]
tdata_test = [96.14,80.12,67.66,57.96,50.90,44.84,39.75,36.16,33.31,31.15,29.28,27.88,27.18,26.40,25.86]
x = np.asarray((xdata))

def dp_c(x,p,g,k,h):
    return np.imag(Ts(x,p+1j*h,g))/h

def dg_c(x,p,g,k,h):
    return np.imag(Ts(x,p,g+1j*h))/h

def sensmat(xdata,p,g):
    k = 2.37
    h = 1e-13
    return np.column_stack((dp_c(xdata,p,g,k,h),dg_c(xdata,p,g,k,h)))


def Ts(x,p,h):
    k = 2.37
    L = 70
    a = b = 0.95
    Ta = 21.29
    y = np.sqrt(2*(a+b)*h/(a*b*k))
    c1 = -p/(k*y)*np.exp(y*L)*(h+k*y)/(np.exp(-y*L)*(h-k*y)+np.exp(y*L)*(h+k*y))
    c2 = p/(k*y) + c1
    return c1*np.exp(-y*x) + c2*np.exp(y*x) + Ta

popt, covt = curve_fit(Ts, xdata, tdata_test, [-18.41,0.00191], maxfev=5000, gtol=0.001)
print("Al parameters = ", popt)
print(covt)

Al parameters =  [-1.84144546e+01  1.91427253e-03]
[[ 1.93887739e-02 -1.87339624e-06]
 [-1.87339624e-06  1.94029479e-10]]


In [103]:
khi = np.asmatrix(sensmat(x,-18.41,0.00191))
khi_t = np.transpose(khi)
multi = khi_t*khi
R = np.transpose(np.asmatrix(tdata_test)) - khi*np.transpose(np.asmatrix(popt))
sigma2 = float(1/13*np.transpose(R)*R)
print("sigma2 = ", sigma2, " wat")

inv = np.linalg.inv(multi)
print(0.0627*inv)

sigma2 =  3200.2892651013112  wat
[[ 2.10404664e-02 -2.02917075e-06]
 [-2.02917075e-06  2.09782059e-10]]


In [104]:
# FOR COPPER

popt, covt = curve_fit(Ts, xdata, tdata, [-18,0.001], maxfev=5000, gtol=0.001)
print("Cu parameters = ", popt)
print(covt)

Cu parameters =  [-5.68037420e+00  7.85619322e-04]
[[ 1.43956088e-03 -1.87084406e-07]
 [-1.87084406e-07  2.62785086e-11]]
